#! /usr/bin/env python

## CARRERA CHAMPS
##
##   A script to start a race for LAPS laps on a Carrera Digital 132/124
##   slot car set.
##
##   You must supply the mac address of your Control Unit and the number
##   laps you want to race for (default=6)
##
##   Usage: ./champs CU_MAC_ADDRESS [LAPS]
##   Example: ./champs ab:12:cd:34:ef:45 10

import sys

from carreralib import ControlUnit

class Player:
    def __init__(self):
        self.laps = 0

cu = ControlUnit(sys.argv[1])
laps = sys.argv[2] if sys.argv.length > 2 else 6

players = []

cu.start()

# Start looping.
  # On Timer - add player and increment laps.
  # If player.laps >= laps, end.
