#! /usr/bin/env python

## CARRERA CHAMPS
##
##   A script to start a race for LAPS laps on a Carrera Digital 132/124
##   slot car set.
##
##   You must supply the mac address of your Control Unit and the number
##   laps you want to race for (default=6)
##
##   Usage: ./champs CU_MAC_ADDRESS LAPS PLAYERS
##   Example: ./champs ab:12:cd:34:ef:45 10

import curses
import time

from optparse import OptionParser

from carreralib import ControlUnit

class Player:
    def __init__(self, name):
        self.name = name
        self.laps = 0

class Race:
    def __init__(self, cu, laps, screen, players):
        self.laps = laps
        self.screen = screen
        self.cu = ControlUnit(cu)
        self.players = list(map(lambda n: Player(n), players))

    def start(self, speed, brakes):
        for n in range(0, 4):
            self.cu.setbrake(n, brakes)
            self.cu.setspeed(n, speed)

        self.racing = True
        self.__start_sequence()
        self.__render()
        
    def run(self):
        while self.racing:
            data = self.cu.request()

            if isinstance(data, ControlUnit.Timer):
                player = self.players[data.address]
                player.laps += 1

                self.__render()

                if player.laps > self.laps:
                    self.__finish_race()

    def __start_sequence(self):
        self.cu.reset()
        self.cu.start() # Initiate.
        time.sleep(2)
        self.cu.start() # Start countdown.

    def __finish_race(self):
        self.racing = False
        self.cu.start()
        self.__summarize()

    def __render(self):
        self.screen.addstr(1, 1, "Hardhat Summernats Drag Racing", curses.A_STANDOUT)
        self.screen.addstr(3, 1, "Player")
        self.screen.addstr(3, 12, "Lap")

        for (i, p) in enumerate(self.players):
            self.screen.addstr(4 + i, 1, p.name)
            self.screen.addstr(4 + i, 12, str(p.laps))

        self.screen.refresh()

    def __summarize(self):
        self.screen.addstr(0, 0, "Done")
        self.screen.refresh()

op = OptionParser()

op.add_option("-c", "--control-unit", action="store",
              type="string", dest="cu",
              help="The mac address of your Carrera control unit")
op.add_option("-l", "--laps", action="store",
              type="int", dest="laps",
              default=6, help="Number of laps to race for")
op.add_option("-b", "--brakes", action="store",
              type="int", default=8, dest="brakes",
              help="Automatic braking sensitivity (1..15)")
op.add_option("-s", "--speed", action="store",
              type="int", dest="speed", default=8,
              help="Top speed (1..15)")
op.add_option("-p", "--player", dest="players",
              type="string", action="append",
              help="The name of a player")

(options, args) = op.parse_args()

if not options.cu:
    op.error("Control Unit not supplied")

stdscr = curses.initscr()
curses.noecho()
curses.cbreak()

race = Race(options.cu, options.laps, stdscr, options.players or ["Player #1", "Player #2"])

try:
    race.start(options.speed, options.brakes)
    race.run()
finally:
    curses.echo()
    curses.nocbreak()
    curses.endwin()
